### ISSUE TITLE
media queries are removed

### ISSUE THREAD

**Issue by GotenXiao** [rennat/pynliner#13]
Given the following sample code:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
        <style type="text/css">
            @media screen and (min-device-width: 480)
            {
                #content
                {
                        width: 480px;
                }
            }
            #content
            {
                border: 1px solid black;
            }
        </style>
    </head>
    <body>
        <div id="content">
            <h1>Hello world</h1>
        </div>
    </body>
</html>
```

I would expect the default border rule to be applied, and the media query hunk to be left alone (since it will only be parsed and used on compatible devices).

As a potential quick fix, pynliner could exclude processing of style or link blocks that have media query-like syntax, or are present and not screen.

**Comment by oppianmatt** [comment]
+1 to merge the PR #38 

Is this project abandoned? No commits since 2014, happy to help maintain if you need someone.

**Comment by rennat** [comment]
not abandoned yet :) just maintained by busy people :(

**Comment by rennat** [comment]
#38 does look good
