### ISSUE TITLE
Style not being applied when multiple elements have same class/Id and same content

### ISSUE THREAD

**Issue by dikesh** [rennat/pynliner#49]
I am facing some weird issue when using `pynliner.fromString(htmlString)`. When multiple elements have same class/Id, it fails to apply CSS rules to all elements except the first one. Here is the sample code with expected output and actual output.

```
<style>
    .text-right {
        text-align: right;
    }
    .box {
        width:200px;
        border: 1px solid #000;
    }
</style>
<div class="box">
    <p>Hello World</p>
    <p class="text-right">Hello World on right</p>
    <p class="text-right">Hello World on right</p>
</div>
```

**Expected Output:**
![image](https://cloud.githubusercontent.com/assets/1618526/17616279/55e43584-6091-11e6-9aa8-fe3e21aceed9.png)

**Actual Output:**
![image](https://cloud.githubusercontent.com/assets/1618526/17616295/6a5c2738-6091-11e6-9971-593419cc7b5f.png)

**Comment by rennat** [comment]
That is indeed odd. I'll be able to devote some time to this pynliner
within a few days and I'll check on this issue

**Comment by tadonis** [comment]
i just fix this problem in my newest push. This is cause by elem_prop_map[element], element hash by element.string, so only one element's style is inlined of the identical elements set.
